apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard

  #eyJhbGciOiJSUzI1NiIsImtpZCI6Ik91Zi1YV0x6UmZPaVJ3RTFSdlZONXFEYTVETG5jUDZCQUlOODRqdnl3U1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLXhtNHJoIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4YWQ0NTViYS1hOTlhLTQ2N2MtYjE0Ni1jZDJkOWIyNWZiNGQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.fqX9vcngBVfjkq_faDY1X9qYG9DSttE3LIjVwydgqBvJkwDAkEwj7kKnJUMdgrzXG6G6knev5n-ls3saVeivVN9XePpX59GpUmkP0kp20-w8YI_XFWZiYh5zX8griNj1LoK8ryxsQTHSlub5Oq93krNWpvkqGV8Y5BG4GkkqPNnrBc54MsLlLi6IQvmSeeH-0NQ8I76b6gMjVvtiB5as2vBnrF3yV_fSFT18dkzELeTO5JQcD9VwaIB8mNaXxlae8KfRt1RIAa8s0aKxRumdns31e_0JI5NA6gY0jO-bis9QTJI3uqyentPqEAOJ7yJfg_tmhZrEsarLAJpUg9Z9CA
  #token above